# Config file for Fundamentals

# Enable or disable modules
enabled:
  checks:
    opchecker: true

  cmds:
    # Player commands
    msg: true
    tpa: true
    tpahere: true

    # Staff commands
    freeze: true
    invsee: true
    staffmsg: true
    staffmode: true
    feed: true
    gamemode: true

tpa:
  # Time it takes for a tp request to expire (default: 600 ticks/30 seconds)
  expiresafter: 600