# Config file for Fundamentals

# Enable or disable modules
enabled:
  checks:
    opchecker: true

  cmds:
    # Player commands
    msg: true
    tpa: true
    tpahere: true
    ignore: true
    welcome: true

    # Staff commands
    broadcast: true
    freeze: true
    invsee: true
    staffmsg: true
    staffmode: true
    feed: true
    gamemode: true
    tpo: true
    fly: true

  chat:
    # Enable global chat, custom joins/leaves, and custom death messages
    globalchat: true
    customjl: true
    customdeaths: true

    # Rules for chat or /msg

    # Allow anything pattern matching a URL
    allowlinks: false
    # Enable auto-formatting of legacy colors, like "&cRed!"
    colors: true
    # Custom regex for disallowed language (like profanity) MAKE SURE THIS IS ESCAPED!
    disallowedregex: "(?<![a-z])(?:(?:(?:[s$5][\\W_]*[h#][\\W_]*[i1!|][\\W_]*[t7+])|(?:sheit)|(?:sh\\*t)|(?:sh\\*\\*)|(?:s\\*\\*t))|(?:(?:f[\\W_]*u[\\W_]*c[\\W_]*k)|(?:fuk)|(?:phuck)|(?:fvck)|(?:f\\*\\*k)|(?:f\\*ck)|(?:f\\*\\*\\*))|(?:(?:c[\\W_]*u[\\W_]*n[\\W_]*[t7+])|(?:c\\*nt)|(?:kunt))|(?:(?:[a@4][\\W_]*[s$5][\\W_]*[s$5])|(?:azz)|(?:@ss))|(?:(?:b[\\W_]*[i1!|][\\W_]*[t7+][\\W_]*c[\\W_]*[h#])|(?:b\\*tch)|(?:biatch))|(?:b[\\W_]*[a@4][\\W_]*[s$5][\\W_]*[t7+][\\W_]*[a@4][\\W_]*r[\\W_]*d)|(?:(?:d[\\W_]*[a@4][\\W_]*m[\\W_]*n)|(?:d@mn))|(?:[h#][\\W_]*[e3][\\W_]*l[\\W_]*l)|(?:p[\\W_]*[i1!|][\\W_]*[s$5][\\W_]*[s$5])|(?:(?:c[\\W_]*[o0][\\W_]*c[\\W_]*k)|(?:c0ck))|(?:(?:d[\\W_]*[i1!|][\\W_]*c[\\W_]*k)|(?:d\\*ck)|(?:dik))|(?:p[\\W_]*u[\\W_]*[s$5][\\W_]*[s$5][\\W_]*y)|(?:(?:n[\\W_]*[i1!|][\\W_]*[g9][\\W_]*[g9][\\W_]*[e3][\\W_]*r)|(?:n\\*gg\\*r)|(?:n\\*gger)|(?:nigga))|(?:f[\\W_]*[a@4][\\W_]*[g9][\\W_]*[g9][\\W_]*[o0][\\W_]*[t7+])|(?:r[\\W_]*[e3][\\W_]*[t7+][\\W_]*[a@4][\\W_]*r[\\W_]*d)|(?:w[\\W_]*[h#][\\W_]*[o0][\\W_]*r[\\W_]*[e3])|(?:[s$5][\\W_]*l[\\W_]*u[\\W_]*[t7+])|(?:c[\\W_]*r[\\W_]*[a@4][\\W_]*p)|(?:w[\\W_]*[a@4][\\W_]*n[\\W_]*k)|(?:[t7+][\\W_]*w[\\W_]*[a@4][\\W_]*[t7+])|(?:b[\\W_]*[o0][\\W_]*l[\\W_]*l[\\W_]*[o0][\\W_]*c[\\W_]*k[\\W_]*[s$5])|(?:[a@4][\\W_]*r[\\W_]*[s$5][\\W_]*[e3])|(?:m[\\W_]*[o0][\\W_]*[t7+][\\W_]*[h#][\\W_]*[e3][\\W_]*r[\\W_]*f[\\W_]*u[\\W_]*c[\\W_]*k[\\W_]*[e3][\\W_]*r)|(?:[a@4][\\W_]*[s$5][\\W_]*[s$5][\\W_]*[h#][\\W_]*[o0][\\W_]*l[\\W_]*[e3])|(?:d[\\W_]*u[\\W_]*m[\\W_]*b[\\W_]*[a@4][\\W_]*[s$5][\\W_]*[s$5])|(?:j[\\W_]*[a@4][\\W_]*c[\\W_]*k[\\W_]*[a@4][\\W_]*[s$5][\\W_]*[s$5])|(?:[s$5][\\W_]*[h#][\\W_]*[i1!|][\\W_]*[t7+][\\W_]*[h#][\\W_]*[e3][\\W_]*[a@4][\\W_]*d)|(?:b[\\W_]*u[\\W_]*l[\\W_]*l[\\W_]*[s$5][\\W_]*[h#][\\W_]*[i1!|][\\W_]*[t7+])|(?:[h#][\\W_]*[o0][\\W_]*r[\\W_]*[s$5][\\W_]*[e3][\\W_]*[s$5][\\W_]*[h#][\\W_]*[i1!|][\\W_]*[t7+])|(?:d[\\W_]*[i1!|][\\W_]*p[\\W_]*[s$5][\\W_]*[h#][\\W_]*[i1!|][\\W_]*[t7+])|(?:f[\\W_]*u[\\W_]*c[\\W_]*k[\\W_]*[h#][\\W_]*[e3][\\W_]*[a@4][\\W_]*d)|(?:c[\\W_]*l[\\W_]*u[\\W_]*[s$5][\\W_]*[t7+][\\W_]*[e3][\\W_]*r[\\W_]*f[\\W_]*u[\\W_]*c[\\W_]*k)|(?:n[\\W_]*[i1!|][\\W_]*[g9][\\W_]*[g9][\\W_]*[a@4])|(?:k[\\W_]*[i1!|][\\W_]*k[\\W_]*[e3])|(?:[s$5][\\W_]*p[\\W_]*[i1!|][\\W_]*c)|(?:c[\\W_]*[h#][\\W_]*[i1!|][\\W_]*n[\\W_]*k)|(?:[g9][\\W_]*[o0][\\W_]*[o0][\\W_]*k)|(?:c[\\W_]*r[\\W_]*[a@4][\\W_]*c[\\W_]*k[\\W_]*[e3][\\W_]*r)|(?:w[\\W_]*[e3][\\W_]*[t7+][\\W_]*b[\\W_]*[a@4][\\W_]*c[\\W_]*k)|(?:[t7+][\\W_]*r[\\W_]*[a@4][\\W_]*n[\\W_]*n[\\W_]*y)|(?:d[\\W_]*y[\\W_]*k[\\W_]*[e3])|(?:f[\\W_]*[a@4][\\W_]*[g9])|(?:b[\\W_]*[e3][\\W_]*[a@4][\\W_]*n[\\W_]*[e3][\\W_]*r)|(?:w[\\W_]*[o0][\\W_]*p)|(?:d[\\W_]*[a@4][\\W_]*[g9][\\W_]*[o0])|(?:[h#][\\W_]*[o0][\\W_]*n[\\W_]*k[\\W_]*y))(?![a-z])"

tpa:
  # Tpa delay before teleport (seconds, can be 0)
  delay: 5
  # Time it takes for a tp request to expire (default: 600 ticks/30 seconds)
  expiresafter: 600

home:
  # Delay before home teleport (seconds, can be 0)
  delay: 5